### ISSUE TITLE
findClusters "memory not mapped"

### ISSUE THREAD

**Issue by Liang-BGI** [thomasp85/densityClust#14]
Hi all.
    l got the "memory not mapped " error when used the findClusters function of densityClust. It works well when using 10K cells, and it gets the error using 50K cells. This is because of the data matrix too large? 

The details of the error as following: 
 dclust <- findClusters(dclust, rho = 30, delta = 1.5)

 *** caught segfault ***
address 0x7fbc3dad5040, cause 'memory not mapped'

Traceback:
 1: findDistValueByRowColInd(x$distance, attr(x$distance, "Size"),     i, higherDensity)
 2: findClusters.densityCluster(dclust, rho = 30, delta = 1.5)
 3: findClusters(dclust, rho = 30, delta = 1.5)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by dpryan79** [comment]
A couple years later I'm running into the same issue. It works with fewer samples/cells. I'll investigate further, but it'll be a bit tough with a CPP R extension.
