### ISSUE TITLE
densityClust producing NA

### ISSUE THREAD

**Issue by jk86754** [thomasp85/densityClust#16]
Hi,

I am trying to run based on the tutorial at
https://rawcdn.githack.com/aertslab/cisTopic/8bb6fc944b041874712714f30fdcbeda3e5c57c6/vignettes/10X_workflow.html

library(Rtsne)
DR_d3 <- Rtsne(t(cellassign_d3), pca=F)
DRdist_d3 <- dist(DR_d3$Y)
library(densityClust)
dclust_d3 <- densityClust(DRdist_d3,gaussian=T)
dclust_d3 <- findClusters(dclust_d3, rho = 50, delta = 2.5)
Error in cluster[i] <- cluster[higherDensity[which.min(findDistValueByRowColInd(x$distance, :
replacement has length zero

I assume this error is produced due to

dclust_d3$clusters
[1] NA

Any ideas on why 'NA' is produced would be appreciated.

please see the objects used above here:

class(cellassign_d3)
[1] "matrix"
dim(cellassign_d3)
[1] 40 2403

DR_d3 looks fine:
image

DRdist_d3:
image

dclust_d3:
image

**Comment by jk86754** [comment]
Images are in issue #15

**Comment by SamGG** [comment]
Hi,
I would think that dclust_d3$clusters being NA is the result of the failure of finding clusters. So, I would try another set of parameters for Rho and delta.
My two cents,
Samuel

**Comment by jk86754** [comment]
You just beat me to the same conclusion. Thank you for the suggestion.
