### ISSUE TITLE
memory.size

### ISSUE THREAD

**Issue by tyluckyma** [thomasp85/densityClust#4]
I'm trying out this algorithm on my dataset. It has around 37,000 data points, and contains only latitude and longitude attribute. My computer has 16GB memory size, and when I try to run the algorithm, it generates the error message saying that:

"
Error: cannot allocate vector of size 5.1 Gb
In addition: Warning messages:
1: In as.matrix.dist(distance) :
  Reached total allocation of 16270Mb: see help(memory.size)
... ...
"

Since this densityClust algorithm is more cheap than DBSCAN literally, and my computer was able to compute DBSCAN (in the "fpc" package) quickly without this memory issue. May I ask can authors improve the algorithm a little bit on this aspect?

**Comment by thomasp85** [comment]
Well 37000*37000 is a lot of numbers to keep in memory. DBSCAN is database - based so it's writing to disk, thus it is not a matter of being more cheap, just simple memory constraint. I'll not rule out that I'll investigate memory optimisations or database backends in the future, but it is not a main concern at the moment...
